version: '3'

services:

  todotests:
    depends_on:
      - todoback
      - todofront
    image: todotests
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - todo-app-network

  todofront:
    ports:
      - 3000:3000
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
    networks:
      - todo-app-network

  todoback:
    ports:
      - 3001:3001
    image: todobackend
    networks:
      - todo-app-network

networks:
  todo-app-network: